{{- if and .Values.secret.create .Values.secret.turnserverConf }}
{{- $secretName := default (printf "%s-config" (include "coturn.fullname" .)) .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
stringData:
  turnserver.conf: |
{{ tpl .Values.secret.turnserverConf . | indent 4 }}
{{- end }}
